variable_labels = {'met_et':r'$\mathrm{E_{T}^{miss}}$ [GeV]',
                      'mllll':r'$\mathrm{m_{4l}}$ [GeV]',
                      'mll':r'$\mathrm{m_{ll}}$ [GeV]',
                      'myy':r'$\mathrm{m_{\gamma\gamma}}$ [GeV]',
                   'ptll':r'$\mathrm{p_{T}^{ll}}$ [GeV]',
                   'delta_eta_ll':r'$\mathrm{\Delta\eta_{ll}}$',
                   'delta_phi_ll':r'$\mathrm{\Delta\phi_{ll}}$',
                   'jet_n':r'$\mathrm{N_{jets}}$',
                   'bjet_n':r'$\mathrm{N_{b-jets}}$',
                   'Channel':'Channel',
                   'SumCharges':r'$\mathrm{\Sigma}$ charge',
                   'MinmOCST':r'min $\mathrm{M_{OCST}}$',
                   'LepPt0':r'$\mathrm{p_{T}^{lep0}}$ [GeV]',
                   'LepPt1':r'$\mathrm{p_{T}^{lep1}}$ [GeV]',
                   'LepPt2':r'$\mathrm{p_{T}^{lep2}}$ [GeV]',
                   'LepPt3':r'$\mathrm{p_{T}^{lep3}}$ [GeV]',
                   'MZ1':r'$\mathrm{M_{Z1}}$ [GeV]',
                   'MZ2':r'$\mathrm{M_{Z2}}$ [GeV]',
                   'H1':'H1',
                   'H1_jet':r'$H1_{jet}$',
                   'Cent_jet':r'$Cent_{jet}$',
                   'eta_ll':r'$\eta_{ll}$',
                   'NVmass_jet_pairs':r'$N^{Vmass}_{jetpairs}$',
                   'N_jet_pt40GeV':r'$N^{jet}_{pT>40GeV}$',
                   'deltaR_jj_ave':r'$\Delta R^{jj}_{ave}$',
                   'pT_3jet':r'$\mathrm{p_{T}^{3jet}}$ [GeV]',
                   'pT_4jet':r'$\mathrm{p_{T}^{4jet}}$ [GeV]',
                   'deltaR_bb':r'$\Delta R^{bb}$',
                   'Mbb':r'$\mathrm{M_{bb}}$ [GeV]',
                   'HT_6jets':r'$\mathrm{H_{T}^{6jets}}$ [GeV]',
                   'pT_6jet':r'$\mathrm{p_{T}^{6jet}}$ [GeV]',
                   'deltaR_ll':r'$\Delta R^{ll}$',
                   'maxM_MindR_lepb':r'max$\mathrm{M^{MindR}_{bb}}$ [GeV]',
                   'M_MindR_jj':r'$\mathrm{M^{MindR}_{jj}}$ [GeV]',
                   'M_W_avg':r'$\mathrm{M^{avg}_{W}}$ [GeV]',
                   'pT_b1':r'$\mathrm{p_{T}^{b1}}$ [GeV]',
                   'N_bjj_top_mass':'Number of top-quark candidates',
                   'pT_5jet':r'$\mathrm{p_{T}^{5jet}}$ [GeV]',
                   'M_Ptord_uu':r'$\mathrm{M^{Ptord}_{uu}}$ [GeV]',
                   'pT_jjj1':r'$\mathrm{p_{T}^{jjj1}}$ [GeV]',
                   'M_jjj1':r'$\mathrm{M_{jjj1}}$ [GeV]',
                   'BDT_output':'BDT output',
                   'NN_output':'NN output',
                   'nJets':r'$\mathrm{N_{jets}}$',
                   'jet_isbtagged_MV2c10_77':'jet_isbtagged_MV2c10_77',
                   'jet_isbtagged_MV2c10_85':'jet_isbtagged_MV2c10_85',
                   'jet_isbtagged_DL1r_77':'jet_isbtagged_DL1r_77',
                   'jet_isbtagged_DL1r_85':'jet_isbtagged_DL1r_85',
                   'jet_charge':r'$\mathrm{Charge_{jet}}$',
                   'jet_e':r'$\mathrm{E_{jet}}$ [MeV]',
                   'jet_eta':r'$\mathrm{\eta_{jet}}$',
                   'jet_nTracks':r'$\mathrm{nTracks_{jet}}$',
                   'jet_phi':r'$\mathrm{\phi_{jet}}$',
                   'jet_pt':r'$\mathrm{p_T^{jet}}$ [MeV]',
                   'jet_truthPartonLabel':r'$\mathrm{truthPartonLabel_{jet}}$',
                   'jet_truthflav':r'$\mathrm{truthflav_{jet}}$',
                   'jet_vtx_charge':r'$\mathrm{vtxCharge_{jet}}$',
                   'met_met':r'$\mathrm{MET}$ [MeV]',
                   'met_phi':r'$\mathrm{\phi_{MET}}$'
}
