FROM continuumio/miniconda3

WORKDIR /opt/app

# Copy the environment.yml file into the container
COPY binder/environment.yml .

RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "analysis", "/bin/bash", "-c"]

# Expose port 8888 for Jupyter Lab
EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]