#
name: Create and publish Docker images

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 'Dockerfile*'
      - 'Dockerfile.rivet'
      - 'binder/environment.yml'
      - '.github/workflows/docker_push.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-matrix-from-changed-files:
    runs-on: ubuntu-latest
    name: Build matrix from changed Dockerfiles
    outputs:
      environments: ${{ steps.set-matrix.outputs.environments }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run changed-files to get modified files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            Dockerfile*
            binder/environment.yml

      - name: Build matrix array
        id: set-matrix
        run: |
          declare -A seen_envs
          environments=()

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"

            if [[ "$file" == "binder/environment.yml" ]] || [[ "$(basename "$file")" == "Dockerfile" ]]; then
              env_name="base"
            else
              # Extract suffix: e.g. Dockerfile.rivet -> rivet
              env_name=$(basename "$file" | sed 's/Dockerfile\.//')
            fi

            # Skip if it's already seen
            if [[ -n "${seen_envs[$env_name]}" ]]; then
              echo " - $env_name already added, skipping"
              continue
            fi

            echo " - $env_name is a new build target, adding it"
            seen_envs[$env_name]=1
            environments+=("\"${env_name}\"")
          done

          # Create comma-separated list formatted as JSON array
          ENVS_LIST="[$(IFS=,; echo "${environments[*]}")]"
          echo "environments=$ENVS_LIST" >> $GITHUB_OUTPUT

          echo "The final list is: ${ENVS_LIST}"

  build-and-push-images:
    needs: build-matrix-from-changed-files
    if: ${{ needs.build-matrix-from-changed-files.outputs.environments != '[]' && needs.build-matrix-from-changed-files.outputs.environments != '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.build-matrix-from-changed-files.outputs.environments) }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.0
        with:
          flavor: |
            latest=false
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=${{ matrix.environment }}-
            type=raw,value=${{ matrix.environment }}-latest,enable=${{ matrix.environment != 'base' }}
            type=raw,value=latest,enable=${{ matrix.environment == 'base' }}
            
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6.0.0
        with:
          context: .
          file: ${{ matrix.environment == 'base' && 'Dockerfile' || format('Dockerfile.{0}', matrix.environment) }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate image attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
