name: Check Jupyter Notebook

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - 13-TeV-examples/**/*ipynb
      - 8-TeV-examples/**/*ipynb
      - for-research/**/*ipynb

jobs:
  detect-changes:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List changed Jupyter Notebook files
        id: changed-notebooks
        run: |
          git fetch origin master
          git diff --name-only origin/master...HEAD | grep ipynb > changed_notebooks.txt
          echo "notebooks=$(cat changed_notebooks.txt | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_ENV

  run-notebooks:
    needs: detect-changes
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        notebook: ${{ fromJson(env.notebooks) }}

    container:
      image: ghcr.io/atlas-outreach-data-tools/notebooks-collection-opendata:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Jupyter kernel
        run: |
          dir_name=$(dirname "${{ matrix.notebook }}")
          kernel="python3"
          
          if [[ "$dir_name" == *cpp ]]; then
            kernel="root"
          fi

          python -m ipykernel install --user --name=$kernel

      - name: Run notebook with Papermill
        run: |
          cd $(dirname ${{ matrix.notebook }})
          papermill $(basename ${{ matrix.notebook }}) /dev/null
